In [2]:
#Write a Python program to check whether a number is even or odd using if-else.

num = int(input("Enter a number: "))

if num % 2 == 0:
    print("The number is even.")
else:
    print("The number is odd.")


Enter a number: 56
The number is even.


In [3]:
#Write a for loop that prints numbers from 10 to 1 in reverse


for i in range(10, 0, -1):
    print(i)

10
9
8
7
6
5
4
3
2
1


In [5]:
#Write a while loop that keeps asking the user to input a number until they enter 0.


number = -1

while number != 0:
    number = int(input("Enter a number "))

Enter a number 2
Enter a number 3
Enter a number 9
Enter a number 0


In [7]:
#Write a function that accepts two numbers and returns their sum.

def add_numbers(a, b):
    return a + b

# Getting input from the user
num1 = int(input("Enter the first number: "))
num2 = int(input("Enter the second number: "))


result = add_numbers(num1, num2)

print("The sum is:", result)


Enter the first number: 67
Enter the second number: 09
The sum is: 76


In [8]:
#What will be the output of this code: print(list(map(lambda x: x*x, [1, 2, 3])))?

print(list(map(lambda x: x*x, [1, 2, 3])))

[1, 4, 9]


In [9]:
#Use the filter() function to extract only even numbers from a list.

numbers = [1, 2, 3, 4, 5, 6]

even_numbers = list(filter(lambda x: x % 2 == 0, numbers))

print("Even numbers:", even_numbers)

Even numbers: [2, 4, 6]


In [11]:
#Explain the purpose of the else block in a try-except-else construct.

try:
    print("Try")
    result = 10 / 0  #
except ZeroDivisionError:
    print("Can't divide by zero.")
else:
    print("The result is:", result)

Try
Can't divide by zero.


In [12]:
#Write a try-except block to handle division by zero.

try:
    number = int(input("Enter a number: "))
    result = 10 / number
    print("Result is:", result)
except ZeroDivisionError:
    print("You can't divide by zero!")


Enter a number: 0
You can't divide by zero!


In [13]:
#What is the output of this lambda function? print((lambda x, y: x+y)(5, 3))

print((lambda x, y: x + y)(5, 3))

8


In [14]:
#Define a class named Dog with properties name and breed. Add a method bark().

class Dog:
    def __init__(self, name, breed):
        self.name = name
        self.breed = breed

    def bark(self):
        print(self.name + "Wooof")

In [16]:
#Create two objects of the Dog class and call their methods.

dog1 = Dog("  Theo  ", "  Golden Retriever  ")
dog2 = Dog("  Goofy  ", "  Labrador  ")

dog1.bark()
dog2.bark()

  Theo  Wooof
  Goofy  Wooof


In [17]:
#What is the difference between class variables and instance variables?

class Example:
    class_var = "Class Variable I am"

    def __init__(self, value):
        self.instance_var = value  # instance variable

In [18]:
#What will this print: print("apple" if 5 > 3 else "banana")?

print("apple" if 5 > 3 else "banana")

apple


In [20]:
#Write a function that accepts a list and returns the list of squares using list comprehension.

def squared(numbers):
    return [x * x for x in numbers]

print(squared([1, 2, 3, 4]))

[1, 4, 9, 16]


In [22]:
#Explain what map() and filter() return when executed.

numbers = [1, 2, 3, 4, 5, 6]

squared = list(map(lambda x: x * x, numbers))
even_list = list(filter(lambda x: x % 2 == 0, numbers))

print("Squares:", squared)
print("Even numbers:", even_list)

Squares: [1, 4, 9, 16, 25, 36]
Even numbers: [2, 4, 6]


**NUMPY**

---



In [24]:
#Create a 3x3 matrix using np.random.randint(0, 10, (3, 3)).

import numpy as np

matrix1 = np.random.randint(0, 10, (3, 3))
print("\n", matrix1)


 [[0 6 7]
 [4 9 9]
 [7 1 8]]


In [25]:

#Slice the above matrix to extract the first two rows.

first_two_rows = matrix1[:2, :]
print("First two rows:\n", first_two_rows)

First two rows:
 [[0 6 7]
 [4 9 9]]


In [26]:
#Combine two 3x3 matrices using np.concatenate along axis 0 and axis 1.

matrix2 = np.random.randint(0, 10, (3, 3))
print("Matrix 2:\n", matrix2)


axis0 = np.concatenate((matrix1, matrix2), axis=0)
print(" axis 0:\n",axis0)

axis1 = np.concatenate((matrix1, matrix2), axis=1)
print("axis 1:\n",axis1)

Matrix 2:
 [[9 0 6]
 [8 5 5]
 [3 2 4]]
 axis 0:
 [[0 6 7]
 [4 9 9]
 [7 1 8]
 [9 0 6]
 [8 5 5]
 [3 2 4]]
axis 1:
 [[0 6 7 9 0 6]
 [4 9 9 8 5 5]
 [7 1 8 3 2 4]]


In [28]:
#Perform element-wise addition, subtraction, and multiplication of two matrices.

matrix = np.random.randint(0, 10, (3, 3))
add = matrix1 + matrix2
sub = matrix1 - matrix2
multiply = matrix1 * matrix2

print("Addition:\n", add)
print("Subtraction:\n", sub)
print("Multiplication:\n", multiply)

Addition:
 [[ 9  6 13]
 [12 14 14]
 [10  3 12]]
Subtraction:
 [[-9  6  1]
 [-4  4  4]
 [ 4 -1  4]]
Multiplication:
 [[ 0  0 42]
 [32 45 45]
 [21  2 32]]


In [29]:
#Demonstrate broadcasting by adding a 1D array to a 2D array.

array_1d = np.array([1, 2, 3])
broadcasted_add = matrix1 + array_1d
print("Broadcasted addition:\n", broadcasted_add)

Broadcasted addition:
 [[ 1  8 10]
 [ 5 11 12]
 [ 8  3 11]]


In [30]:
#Use np.clip to limit values in a matrix to a minimum of 2 and maximum of 8.

arr= np.clip(matrix1, 2, 8)
print("\n",arr)


 [[2 6 7]
 [4 8 8]
 [7 2 8]]


In [31]:
#Use np.ceil on an array of floating-point numbers [1.2, 2.5, 3.8].

floats = np.array([1.2, 2.5, 3.8])
ceiled = np.ceil(floats)
print("\n", ceiled)


 [2. 3. 4.]


In [32]:
#Use np.where to replace all elements greater than 5 with 100 in a given array.

modified = np.where(matrix1 > 5, 100, matrix1)
print("\n", modified)


 [[  0 100 100]
 [  4 100 100]
 [100   1 100]]


In [33]:
#Create two 2x2 matrices and compute their dot product.

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

dot_product = np.dot(a, b)
print("Dot product:\n", dot_product)

Dot product:
 [[19 22]
 [43 50]]


In [34]:
#What is the difference between np.array([1, 2, 3]) and np.array([[1, 2, 3]])?

arr1 = np.array([1, 2, 3])
arr2 = np.array([[1, 2, 3]])

print("Shape of arr1:", arr1.shape)
print("Shape of arr2:", arr2.shape)

Shape of arr1: (3,)
Shape of arr2: (1, 3)
